// Generated by LiveScript 1.3.1
$('.carousel').carousel();
xfl.load('https://plotdb.github.io/xl-fontset/alpha/王漢宗細圓/', function(font){
  return font.sync(document.body.innerText, function(){
    console.log(font);
    return document.body.style.fontFamily = ['c0nsolas', 'Varela Round', 'Helvetica', 'Arial', font.name, 'sans-serif'].map(function(it){
      return "\"" + it + "\"";
    }).join(',');
  });
});