// Generated by LiveScript 1.3.1
var fonturl;
smoothScroll();
fonturl = {
  root: 'https://plotdb.github.io/xl-fontset/alpha',
  content: '源石黑體-Light',
  heading: '王漢宗超明'
};
xfl.load(fonturl.root + "/" + fonturl.content + "/", function(font){
  return font.sync(document.body.innerText, function(){
    return xfl.load(fonturl.root + "/" + fonturl.heading + "/", function(font){
      var texts;
      texts = Array.from(document.querySelectorAll('h1,h2,h3,h4,h5,h6')).map(function(it){
        return it.innerText;
      }).join('');
      return font.sync(texts, function(){});
    });
  });
});